### ISSUE TITLE
The PDF Group View for folders is broken in Plone 6 branch

### ISSUE THREAD

**Issue by gotcha** [collective/collective.documentviewer#90]
```  
...
Module collective.documentviewer.browser.views, line 395, in results
  Module collective.documentviewer.browser.views, line 388, in getContents
AttributeError: 'RequestContainer' object has no attribute 'getFolderContents'
```

**Comment by jladage** [comment]
Hi @gotcha how are you? I refactored the PDF group view and have it working on Plone6.1. It's been a while since I've committed anything and I'm still not good at tests. Would you be so kind to review my commits and look at the tests?
